resources:
  - https://raw.githubusercontent.com/tailscale/tailscale/refs/tags/v1.96.5/cmd/k8s-operator/deploy/manifests/operator.yaml
patches:
  - target:
      kind: Secret
      name: operator-oauth
      namespace: tailscale
    patch: |-
      apiVersion: v1
      kind: Secret
      metadata:
        name: operator-oauth
        namespace: tailscale
      $patch: delete
