apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ovumcy
  annotations:
    tailscale.com/hostname: placeholder
spec:
  ingressClassName: tailscale
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ovumcy
                port:
                  number: 8080
