apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ovumcy
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./kubernetes/infrastructure/ovumcy
  prune: true
  wait: true
  timeout: 5m
  patches:
    - patch: |
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: ovumcy
          namespace: ovumcy
        spec:
          tls:
          - hosts:
            - nginx
      target:
        kind: Ingress
        name: ovumcy
