apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
spec:
  cluster:
    domain: "cluster.local"
  sync:
    path: "./kubernetes/clusters/homelab"
