cert-manager:
  enabled: false
lvmd:
  args: ["--lvm-path", "/run/current-system/sw/bin/lvm"]
  managed: true
  deviceClasses:
    - name: default
      default: true
      spare-gb: 10
node:
  args: ["--lvm-path", "/run/current-system/sw/bin/lvm"]
storageClasses:
  - name: topolvm-provisioner
    storageClass:
      fsType: xfs
      isDefaultClass: true
      volumeBindingMode: WaitForFirstConsumer
      allowVolumeExpansion: true
      additionalParameters:
        "topolvm.io/device-class": "default"
