apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: golinky
spec:
  defaultBackend:
    service:
      name: golinky
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - home
