apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: golinky
spec:
  ingressClassName: tailscale
  rules:
    - host: home
      http:
        paths:
          - backend:
              service:
                name: golinky
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - home
